games/urls.py
# pylint: disable=E1120, C0103
from django.conf.urls import url
from django.views.generic import TemplateView
from games import views


urlpatterns = [
    url(r'^$',
        views.GameList.as_view(),
        name='game_list'),
    url(r'^year/(\d+)/$',
        views.GameListByYear.as_view(),
        name='games_by_year'),
    url(r'^genre/([\w-]+)/$',
        views.GameListByGenre.as_view(),
        name='games_by_genre'),
    url(r'^by/([\w-]+)/$',
        views.GameListByCompany.as_view(),
        name='games_by_company'),
    url(r'^platform/(?P<slug>[\w\-]+)/$',
        views.GameListByPlatform.as_view(),
        name="games_by_plaform"),
    url(r'^publish/(?P<id>\d+)$',
        views.publish_game,
        name='game-publish'),
    url(r'^add-game/$',
        views.submit_game,
        name='game-submit'),
    url(r'^game-submitted',
        TemplateView.as_view(template_name='games/submitted.html'),
        name="game-submitted"),

    url('^game-issue',
        views.submit_issue,
        name='game-submit-issue'),
    url(r'banner/(?P<slug>[\w\-]+).jpg',
        views.get_banner,
        name='get_banner'),
    url(r'icon/(?P<slug>[\w\-]+).png',
        views.get_icon,
        name='get_icon'),
    url(r'install/(?P<id>[\d]+)/view$',
        views.view_installer,
        name='view_installer'),
    url(r'install/(?P<id>[\d]+)/fork$',
        views.fork_installer,
        name='fork_installer'),
    url(r'install/(?P<slug>[\w\-]+)/$',
        views.get_installers,
        name='get_installers'),

    # Legacy URLs, do be removed with Lutris 0.4
    url(r'install/(?P<slug>[\w\-]+).yml$',
        views.serve_installer,
        name='serve_installer'),  # Legacy yaml installer url
    url(r'install/(?P<slug>[\w\-]+).jpg$',
        views.serve_installer_banner,
        name='serve_installer_banner'),  # Legacy banner url
    url(r'install/icon/(?P<slug>[\w\-]+).png$',
        views.serve_installer_icon,
        name='serve_installer_icon'),  # Legacy icon url

    url(r'(?P<slug>[\w\-]+)/installer/new/$',
        views.new_installer,
        name="new_installer"),
    url(r'(?P<slug>[\w\-]+)/installer/edit/$',
        views.edit_installer,
        name='edit_installer'),
    url(r'(?P<slug>[\w\-]+)/installer/publish/$',
        views.publish_installer,
        name='publish_installer'),
    url(r'(?P<slug>[\w\-]+)/installer/complete/$',
        views.installer_complete,
        name='installer_complete'),
    url(r'installer/feed/$',
        views.InstallerFeed(),
        name='installer_feed'),

    url(r'([\w\-]+)/screenshot/add/',
        views.screenshot_add,
        name='screenshot_add'),
    url(r'screenshot/(?P<id>\d+)/publish/$',
        views.publish_screenshot,
        name='publish_screenshot'),

    url(r'game-for-installer/(?P<slug>[\w\-]+)/',
        views.game_for_installer,
        name='game_for_installer'),
    url(r'(?P<slug>[\w\-]+)/$',
        views.game_detail,
        name="game_detail"),
]

lutrisweb/urls.py
"""Main URLconf"""
# pylint: disable=C0103
import logging
from importlib import import_module

from django.conf import settings
from django.urls import include, re_path, path
from django.contrib import admin
from django.views.static import serve
from django_openid_auth.views import login_begin
from rest_framework.authtoken.views import obtain_auth_token

from bundles.views import BundleView
from common.views import server_status

logger = logging.getLogger(__name__)
admin.autodiscover()


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/games/', include('games.urls.admin')),
    path('admin/', admin.site.urls),
    path('select2/', include('django_select2.urls')),
    path('openid/', include('django_openid_auth.urls')),
    path('user/', include('accounts.urls')),

    path('api/accounts/token', obtain_auth_token, name='accounts_get_token'),
    path(
        'api/accounts/auth',
        include('rest_framework.urls', namespace='rest_framework')
    ),
    path('api/tosec', include('tosec.urls')),
    path('api/hardware', include('hardware.urls')),
    path('api/runners', include('runners.runner_urls')),
    path('api/runtimes', include('runners.runtime_urls')),
    path('api/games', include('games.urls.games')),
    path('api/installers', include('games.urls.installers')),
    path('api/users', include('accounts.urls_api')),
    path('api/providers', include('providers.urls')),
    path('api/bundles/<slug:slug>', BundleView.as_view(), name='api_bundle_view'),
    path('games', include('games.urls.pages')),
    path('bundles', include('bundles.urls')),
    path('email/', include('emails.urls')),
    path(
        'steam-login/',
        login_begin,
        kwargs={'login_complete_view': 'associate_steam'},
        name='steam_login'
    ),
    path('server-status', server_status, name='server_status'),
    path('', include('common.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve,
                {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    ]

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

signal_modules = {}

for app in settings.INSTALLED_APPS:
    signals_module = '%s.signals' % app
    try:
        signal_modules[app] = import_module(signals_module)
    except ImportError:
        pass

games/models.py
"""Models for main lutris app"""

# pylint: disable=no-member,too-few-public-methods,too-many-lines
import os
import shutil
import datetime
import json
import logging
import random
import re
from itertools import chain

import six
import yaml
from bitfield import BitField
from sorl.thumbnail import get_thumbnail
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.core.files.base import ContentFile
from django.db import models, IntegrityError
from django.db.models import Count, Q
from django.db.models.query import QuerySet
from django.urls import reverse

from common.cloudflare import purge_urls
from common.util import get_auto_increment_slug, slugify, load_yaml, dump_yaml
from emails import messages
from emails.messages import notify_rejected_installer
from games.util import steam, gog
from platforms.models import Platform
from runners.models import Runner
from providers.models import ProviderGame


LOGGER = logging.getLogger(__name__)
DEFAULT_INSTALLER = {
    "files": [{"file_id": "http://location"}, {"unredistribuable_file": "N/A"}],
    "installer": [{"move": {"src": "file_id", "dst": "$GAMEDIR"}}],
}


def clean_string(string):
    return string.replace("\r\n", "\n").strip()


class Company(models.Model):
    """Gaming company"""

    name = models.CharField(max_length=127)
    slug = models.SlugField(unique=True)
    logo = models.ImageField(upload_to="companies/logos", blank=True)
    website = models.CharField(max_length=128, blank=True)

    class Meta:
        """Additional configuration for model"""

        verbose_name_plural = "companies"
        ordering = ["name"]

    def get_absolute_url(self):
        """Return URL to a company's games"""
        return reverse("games_by_company", kwargs={"company": self.pk})

    def __str__(self):
        return str(self.name)

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        if self.name:
            self.slug = slugify(self.name)
        if not self.slug:
            raise ValueError("Tried to save Company without a slug: %s" % self)
        return super(Company, self).save(
            force_insert=force_insert,
            force_update=force_update,
            using=using,
            update_fields=update_fields,
        )

    @staticmethod
    def autocomplete_search_fields():
        """Autocomplete fields used in the Django admin"""
        return ("name__icontains", "slug__icontains")


class Genre(models.Model):
    """Gaming genre"""

    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)

    class Meta:
        """Model configuration"""

        ordering = ["name"]

    def __str__(self):
        return str(self.name)

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        if not self.slug:
            self.slug = slugify(self.name)
        return super(Genre, self).save(
            force_insert=force_insert,
            force_update=force_update,
            using=using,
            update_fields=update_fields,
        )

    @staticmethod
    def autocomplete_search_fields():
        """Autocomplete fields used in the Django admin"""
        return ("name__icontains",)


class GameManager(models.Manager):
    """Model manager for Game"""

    class Meta:
        """Model configuration"""

        ordering = ["name"]

    def published(self):
        """Query games that are published"""
        return self.get_queryset().filter(change_for__isnull=True, is_public=True)

    def with_installer(self):
        """Query games that have an installer"""
        return (
            self.get_queryset()
            .filter(change_for__isnull=True)
            .filter(is_public=True)
            .filter(
                Q(installers__published=True)
                | Q(platforms__default_installer__startswith="{")
                | Q(provider_games__provider__name__in=("gog", "steam", "humble"))
            )
            .order_by("name")
            .annotate(installer_count=Count("installers", distinct=True))
        )

    def get_random(self, option=""):
        """Return a random game"""
        if not re.match(r"^[\w\d-]+$", option) or len(option) > 128:
            return None
        pk_query = self.get_queryset()
        if option == "incomplete":
            pk_query = pk_query.filter(change_for__isnull=True, year=None)
        elif option == "published":
            pk_query = self.with_installer()
        elif len(option) > 1:
            pk_query = pk_query.filter(
                Q(platforms__slug=option) | Q(installers__runner__slug=option)
            )
        pks = pk_query.values_list("pk", flat=True)
        if not pks:
            return None
        random_pk = random.choice(pks)
        return self.get_queryset().get(pk=random_pk)


class Game(models.Model):
    """Game model"""

    GAME_FLAGS = (
        ("fully_libre", "Fully libre"),
        ("open_engine", "Open engine only"),
        ("free", "Free"),
        ("freetoplay", "Free-to-play"),
        ("pwyw", "Pay what you want"),
        ("kernel_ac", "Infected with kernel level anticheat"),
        ("adult_only", "Adult only"),
    )

    # These model fields are editable by the user
    TRACKED_FIELDS = [
        "name",
        "year",
        "platforms",
        "genres",
        "publisher",
        "developer",
        "website",
        "description",
        "title_logo",
    ]

    ICON_PATH = os.path.join(settings.MEDIA_ROOT, "game-icons/128")
    BANNER_PATH = os.path.join(settings.MEDIA_ROOT, "game-banners/184")

    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True, null=True, blank=True)
    year = models.PositiveSmallIntegerField(null=True, blank=True)
    platforms = models.ManyToManyField(Platform, blank=True)
    genres = models.ManyToManyField(Genre, blank=True)
    publisher = models.ForeignKey(
        Company,
        related_name="published_game",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )
    developer = models.ForeignKey(
        Company,
        related_name="developed_game",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )
    website = models.CharField(max_length=200, blank=True)
    icon = models.ImageField(upload_to="uploads/icons", blank=True)
    title_logo = models.ImageField(upload_to="uploads/banners", blank=True)
    coverart = models.ImageField(upload_to="igdb", blank=True)
    description = models.TextField(blank=True)
    is_public = models.BooleanField("Published", default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    steamid = models.PositiveIntegerField(null=True, blank=True)
    gogslug = models.CharField(max_length=200, blank=True)
    gogid = models.PositiveIntegerField(null=True, blank=True)
    humblestoreid = models.CharField(max_length=200, blank=True)
    flags = BitField(flags=GAME_FLAGS)
    popularity = models.IntegerField(default=0)
    provider_games = models.ManyToManyField(
        ProviderGame, related_name="games", blank=True
    )

    # Indicates whether this data row is a changeset for another data row.
    # If so, this attribute is not NULL and the value is the ID of the
    # corresponding data row
    change_for = models.ForeignKey(
        "self", null=True, blank=True, on_delete=models.CASCADE
    )

    # Adding Discord App ID for Rich Presence Client
    discord_id = models.CharField(
        max_length=18,
        default="",
        null=True,
        blank=True,
    )

    objects = GameManager()

    class Meta:
        """Model configuration"""

        ordering = ["name"]
        permissions = (("can_publish_game", "Can publish game"),)

    @classmethod
    def valid_fields(cls):
        """Return a list of valid field names for the model"""
        return [f.name for f in cls._meta.fields]

    def __str__(self):
        if self.change_for is None:
            return self.name
        return "[Changes for] " + self.change_for.name

    @staticmethod
    def autocomplete_search_fields():
        """Autocomplete fields used in the Django admin"""
        return ("name__icontains",)

    @property
    def humbleid(self):
        """Humble Bundle ID, different from humblestoreid (store page ID for Humble Bundle)
        This should really get deprecated.
        """
        _slugs = self.provider_games.filter(provider__name="humblebundle").values_list(
            "slug", flat=True
        )
        if _slugs:
            return _slugs[0]
        return ""

    @property
    def user_count(self):
        """How many users have the game in their libraries"""
        return self.librarygame_set.count()

    @property
    def website_url(self):
        """Returns self.website guaranteed to be a valid URI"""
        if not self.website:
            return None

        # Fall back to http if no protocol specified (cannot assume that https will work)
        has_protocol = "://" in self.website
        return "http://" + self.website if not has_protocol else self.website

    @property
    def website_url_hr(self):
        """Returns a human readable website URL (stripped protocols and trailing slashes)"""
        if not self.website:
            return None
        return self.website.split("https:", 1)[-1].split("http:", 1)[-1].strip("/")

    @property
    def banner_url(self):
        """Return URL for the game banner"""
        if self.title_logo:
            # Hardcoded domain isn't ideal but we have to find another solution for storing
            # and referencing banners and icons anyway so this will do for the time being.
            if self.change_for:
                slug = self.change_for.slug
            else:
                slug = self.slug

games/views/achievements.py
from __future__ import absolute_import

from rest_framework import filters, generics, permissions
from rest_framework.response import Response
from django.http import JsonResponse

from games import models, serializers

class UnlockAchievementView(generics.GenericAPIView):

    def get(self, request, achievement_id):
        return JsonResponse({'message':'achievement was unlocked'})

class GetAchievementsView(generics.GenericAPIView):

    def get(self, request, username, achievement_id):
        return JsonResponse({
                              "achivements":
                              [
                                {
                                  'completed': True,
                                  'achievement':
                                  {
                                    'id': 101, 'name': "Win the game", 'Description': "Just win",
                                    'achieved_icon': "game/321/win.png", 'unachieved_icon': "game/321/win.png",
                                    'progress_stat':None
                                  }
                                },
                                {
                                  'completed': False,
                                  'achievement':
                                  {
                                    'id': 102, 'name': "Win 100 times", 'Description': "Just over and over again",
                                    'achieved_icon': "game/321/100wins.png", 'unachieved_icon': "game/321/100wins.png",
                                    'progress_stat':
                                    {
                                      'stat_id': 321, 'stat_name': "wins",'min_value': 0, 'max_value': 100, 'current_value': 56
                                    }
                                  }
                                }
                              ]
                            })

templates/games/_draft.html
{% load lutris %}
{% load humanize %}
{% load static %}

<li class="list-group-item bg-darker draft-border">
  <div>
    <div class="btn-group right">
        <a type="button" class="btn btn-sm btn-secondary" href="lutris:{{ installer.game.slug }}?revision={{installer.id}}">Install</a>
        <button
          type="button"
          class="btn btn-sm btn-secondary dropdown-toggle dropdown-toggle-split"
          id="dropdownMenuReference"
          data-bs-toggle="dropdown"
          aria-expanded="false"
          data-bs-reference="parent">
          <span class="visually-hidden">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuReference">
          <li><a class="dropdown-item bg-dark text-white" href="{% url 'edit_draft' draft_id=installer.id %}">
            Edit installer
          </a></li>
        </ul>
    </div>
    <div class="centered-vertical">
      <span class='filter-link'>{{ installer.runner }}</span>
      <span class='installer-name'>{{ installer.version|capfirst }} version</span>
      <small class="text-muted">
        {% if user.is_staff %}
        <a href="{{ DASHBOARD_URL }}/#/installers/submissions/{{installer.id}}"
            class="btn btn-sm btn-danger">Review installer</a>
        {% endif %}
      </small>
    </div>
  </div>

  {% if installer.description.strip %}
  <div><strong>{{ installer.description|clean_html|safe|linebreaksbr }}</strong></div>
  {% endif %}

  {% if installer.notes.strip %}
  <div class="small-text">{{ installer.notes|clean_html|safe|linebreaksbr }}</div>
  {% endif %}
</li>

templates/games/_installer.html
{% load lutris %}
{% load humanize %}
{% load static %}

<li class="list-group-item bg-darker{% if installer.draft %} draft-border{% endif %}">
  <div>
    <div class="btn-group right">
      <a type="button" class="btn btn-sm btn-secondary" href="lutris:{{ installer.slug }}">Install</a>
      {% if not installer.auto %}
        <button
          type="button"
          class="btn btn-sm btn-secondary dropdown-toggle dropdown-toggle-split"
          id="dropdownMenuReference"
          data-bs-toggle="dropdown"
          aria-expanded="false"
          data-bs-reference="parent">
          <span class="visually-hidden">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuReference">
          <li><a class="dropdown-item bg-dark text-white" href="{% url 'edit_installer' slug=installer.slug %}">
            Edit installer
          </a></li>
          {% if user.is_staff %}
            <li><a class="dropdown-item bg-dark text-white" href="{% url 'admin:games_installer_change' installer.id %}">
              Admin installer
            </a></li>
          {% endif %}

          {% if installer.id %}
            <li><a class="dropdown-item bg-dark text-white" href="{% url 'view_installer' id=installer.id %}">
              View install script
            </a></li>
          {% endif %}
          <li><a class="dropdown-item bg-dark text-white" href="{% url 'api_game_installer_list' slug=installer.slug %}?format=json">
            Download script
          </a></li>
        </ul>
      {% endif %}
    </div>
    <div class="centered-vertical">

      <span class='filter-link'>{{ installer.runner }}</span>

      <span class='installer-name'>{{ installer.version|capfirst }} version</span>
      <span class="small-text">
        {% if installer.is_playable == True %}
        Rating: ✅ <strong>PLAYABLE</strong>{% elif installer.is_playable == False %}
        Rating: ❌ <strong>NOT PLAYABLE</strong>{% endif %}
      </span>
      <small class="text-muted">
        {% if installer.updated_at %}last published {{ installer.updated_at | naturaltime }}{% endif %}
        {% if installer.latest_version %}, last edit made {{ installer.latest_version.revision.date_created | naturaltime }}
          {% if user.is_staff %}
            <a href="{{ DASHBOARD_URL }}/#/installers/submissions/{{installer.latest_version.revision.id}}"
              class="btn btn-sm btn-danger">Review installer</a>
          {% endif %}
        {% endif %}
      </small>
    </div>
  </div>
  {% if installer.flagged %}
  <div class="danger-zone"><strong>☠️ THIS INSTALLER HAS BEEN FLAGGED AS POTENTIALLY UNSAFE.<br>USE WITH EXTREME CAUTION ☠️</strong></div>
  {% endif %}
  {% if installer.description.strip %}
  <div><strong>{{ installer.description|clean_html|safe|linebreaksbr }}</strong></div>
  {% endif %}


  {% if installer.notes.strip %}
  <div class="small-text">{{ installer.notes|clean_html|safe|linebreaksbr }}</div>
  {% endif %}

</li>

templates/games/_mini_game_preview.html
{% load thumbnail %}

<div class='game-banner m-2'>
  <a href="{{ game.get_absolute_url }}" title="{{game.name}}">
    {% thumbnail game.title_logo '184x69' crop="center" as img %}
      <img class='game-cover' src='{{ img.url }}' alt='No image'/>
    {% empty %}
      <span class='game-cover'>no image</span>
    {% endthumbnail %}
    <span class='game-title'>{{game.name}}</span>
  </a>
</div>

templates/games/game_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% load append_to_get %}


{% block title %}Games | Lutris{% endblock %}


{% block content %}
<div class="row">
  <div class="col-lg-9">
    {% if games %}
      {% for game in games %}
        {% include "includes/game_preview.html" %}
      {% endfor %}
    {% else %}
      <div class="alert alert-info mx-auto d-table">
        No games found that match these criteria.
        Feel free to <a href="{% url 'game-submit' %}" class="btn btn-sm btn-primary">add the game</a> to our database.
      </div>
    {% endif %}
  </div>
  <div class="col-lg-3">
    <div class="paginator-options filter-form">
      <span class="px-2">Results per page:</span>
      <select id="paginate_by" onchange="updatePaginateBy(this)">
          <option value="25" {% if paginate_by == 25 %} selected {% endif %}>25</option>
          <option value="50" {% if paginate_by == 50 %} selected {% endif %}>50</option>
          <option value="100" {% if paginate_by == 100 %} selected {% endif %}>100</option>
      </select>
      <br><br>
      <span class="px-2">Sort by:</span>
      <select id="order_by" onchange="updateSort(this)">
        <option value="name" {% if order_by == 'name' %} selected {% endif %}>Name (A-Z)</option>
        <option value="-name" {% if order_by == '-name' %} selected {% endif %}>Name (Z-A)</option>
        <option value="year" {% if order_by == 'year' %} selected {% endif %}>Oldest first</option>
        <option value="-year" {% if order_by == '-year' %} selected {% endif %}>Newest first</option>
        <option value="-updated" {% if order_by == '-updated' %} selected {% endif %}>Recently updated</option>
        <option value="-created" {% if order_by == '-created' %} selected {% endif %}>Recently added</option>
        <option value="-popularity" {% if order_by == '-popularity' %} selected {% endif %}>Popularity</option>
      </select>
    </div>
    <div class="filter-form">
      <form action="{% url 'game_list' %}" method="get" id="library_filter_form">
        {{ filter_form.as_p }}
        <label for="search-installers" style="margin-bottom: 1em;margin-top: 0;">
          <input type="checkbox" id="search-installers" name="search-installers"
              {% if search_installers %}checked{% endif %} />
          Search in installers
        </label>
        <div>
          <input type="submit" value="Search" class="btn btn-primary">
        </div>
      </form>
    </div>
    <div>
      <p class="py-4">
        If we don't have the game in our database, you can
        <a href="{% url 'game-submit' %}" class="action-button margin-auto hidden-xs">submit a new game</a>.
      </p>
    </div>
  </div>
</div>

{% if page_obj.has_other_pages %}
<div class="centered">
    {% include 'includes/library_paginator.html' %}
</div>
{% endif %}

{% endblock %}

{% block scripts %}
  {{ block.super }}
  {{ filter_form.media.js }}
  <script>
    const URL = "{% url 'game_list' %}"
    function updateSort(elem) {
      let params = new URLSearchParams(document.location.search);
      params.set("ordering", elem.value)
      window.location.replace(URL + "?" + params.toString())
    }
    function updatePaginateBy(elem) {
      let params = new URLSearchParams(document.location.search);
      params.set("paginate_by", elem.value)
      window.location.replace(URL + "?" + params.toString())
    }
  </script>
{% endblock %}

templates/games/installer-delete.html
{% extends "base.html" %}
{% block content %}
<div class="row">
<div class="message-view col-md-6 col-md-offset-3">
  <p>
    Are you sure you want to delete <strong>{{installer}}</strong>?<br/>
  </p>
  <form method="POST">
    {% csrf_token %}
    <input type="submit" name="delete" id="delete" value="Yes, delete it!" class="btn btn-danger" />
    <a class="btn btn-primary" href="{{ installer.game.get_absolute_url }}">No, cancel that!</a>
  </form>
</div>
</div>
{% endblock %}

templates/games/submit.html
{% extends "base.html" %}
{% load static %}


{% block title %}
{% if not game %}Submit a new game{% else %}Suggest changes{% endif %} - Lutris
{% endblock %}


{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/croppie.css' %}" />
{{ form.media.css }}
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-10 col-lg-offset-1">

    <div class="form-view">
      <h1>
        {% if not game %}
        Submit a game
        {% else %}
        Suggest changes to '{{ game.name }}'
        {% endif %}
      </h1>
      {% if game %}
      <p class="warning">If you abuse this form to report bugs, we will disable your Lutris account.</p>
      {% else %}
      <p class="warning">
        Please check the spelling of the game you're adding. Do not use an abbreviated version of a name.
        Submissions that we judge have been sent in bad faith can get your Lutris account deleted.
      </p>
      {% endif %}
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% if game %}
          <div id="div_id_reason" class="form-group">
            {{ form.reason.errors }}
            {{ form.reason.label_tag }}
            {{form.reason}}
          </div>
        {% endif %}
          <div id="div_id_name" class="form-group">
            {{ form.name.errors }}
            {{ form.name.label_tag }}
            <div>
              {{form.name}}
            </div>
          </div>
          <div id="div_id_year" class="form-group">
            {{form.year.errors}}
            <label for="{{form.year.id_for_label }}">Release year</label>
            <div>
              {{form.year}}
            </div>
          </div>
          <div id="div_id_developer" class="form-group">
            {{ form.developer.errors }}
            {{ form.developer.label_tag }}
            {{ form.developer }}
          </div>
          <div id="div_id_publisher" class="form-group">
            {{ form.publisher.errors }}
            {{ form.publisher.label_tag }}
            {{ form.publisher }}
          </div>
          <div id="div_id_website" class="form-group">
            {{ form.website.errors }}
            {{ form.website.label_tag }}
            {{ form.website }}
            <small id="hint_id_website" class="form-text text-muted">
              The official website (full address). If it doesn't exist, leave blank.
            </small>
          </div>
          <div id="div_id_platforms" class="form-group">
            {{ form.platforms.errors }}
            {{ form.platforms.label_tag }}
            {{ form.platforms }}
          </div>
          <div id="div_id_genres" class="form-group">
            {{ form.genres.errors }}
            {{ form.genres.label_tag }}
            {{ form.genres }}
          </div>
          <div id="div_id_description" class="form-group">
            {{ form.description.errors }}
            {{ form.description.label_tag }}
            {{ form.description }}
            <small id="hint_id_description" class="form-text text-muted">
              Copy the official description of the game if you can find it.
              Don't write your own. For old games, check Mobygame's Ad Blurbs, look for the English back cover text.
            </small>
          </div>
          <div id="div_id_title_logo" class="form-group">
            <div class="controls file-upload-button ">
              {{ form.title_logo.errors }}
              <label for="id_title_logo" class="upload-button">
                Game title (184x69 image format):
              </label>
              {{ form.crop_data }}
              {{ form.title_logo }}
              <div id="cropper" style="display: none"></div>
              <p>
                <small id="hint_id_title_logo" class="form-text text-muted">
                  The banner should include the game's title.
                  Please make sure that your banner doesn't rely on transparency
                  as those won't be reflected in the final image
                </small>
              </p>
            </div>
          </div>
          <div>
            <input type="submit" name="submit" value="Submit" class="btn btn-primary" id="submit-id-submit">
          </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}


{% block scripts %}
<script src="{% static 'js/croppie.min.js' %}"></script>
{{ block.super }}
{{ form.media.js }}

<script>
  let $uploadCrop = $('#cropper').croppie({
    enableExif: true,
    mouseWheelZoom: false,
    viewport: {
        width: 736,
        height: 276
    },
    boundary: {
        width: 736,
        height: 276
    }
  })

  $('#cropper').on('update.croppie', function(ev, cropData) {
    $("#id_crop_data").val(JSON.stringify(cropData))
  })

  $('#id_title_logo').on('change', function () {
    $('#cropper').show()
    var reader = new FileReader();
    reader.onload = function (e) {
      $uploadCrop.croppie('bind', {
        url: e.target.result
      }).then(function(){

       });
    }
    reader.readAsDataURL(this.files[0]);
  });

  $(function () {
    $('#id_platforms').select2({
      closeOnSelect: false,
      placeholder: ''
    });
    $('#id_genres').select2({
      closeOnSelect: false,
      placeholder: ''
    });
  });
</script>
{% endblock %}